from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from UI.user_interface.music import Sound
class AboutWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.text_label_6 = QtWidgets.QLabel(self.centralwidget)
        self.text_label_6.setGeometry(QtCore.QRect(170, 200, 461, 61))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(18)
        self.text_label_6.setFont(font)
        self.text_label_6.setObjectName("text_label_6")
        self.text_label_7 = QtWidgets.QLabel(self.centralwidget)
        self.text_label_7.setGeometry(QtCore.QRect(170, 280, 461, 61))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(18)
        self.text_label_7.setFont(font)
        self.text_label_7.setObjectName("text_label_7")
        self.text_label_8 = QtWidgets.QLabel(self.centralwidget)
        self.text_label_8.setGeometry(QtCore.QRect(170, 360, 461, 61))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(18)
        self.text_label_8.setFont(font)
        self.text_label_8.setObjectName("text_label_8")
        self.text_label_9 = QtWidgets.QLabel(self.centralwidget)
        self.text_label_9.setGeometry(QtCore.QRect(170, 440, 461, 61))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(18)
        self.text_label_9.setFont(font)
        self.text_label_9.setObjectName("text_label_9")      
    
        self.text_label_10 = QtWidgets.QLabel(self.centralwidget)
        self.text_label_10.setGeometry(QtCore.QRect(170, 520, 461, 61))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(18)
        self.text_label_10.setFont(font)
        self.text_label_10.setObjectName("text_label_10")

        self.Help_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.Help_label_3.setGeometry(QtCore.QRect(230, 40, 341, 131))
        font = QtGui.QFont()
        font.setFamily("Freestyle Script")
        font.setPointSize(72)
        self.Help_label_3.setFont(font)
        self.Help_label_3.setObjectName("Help_label_3")
        self.text_label_6.raise_()
        self.text_label_7.raise_()
        self.text_label_8.raise_()
        self.text_label_9.raise_()
        self.text_label_10.raise_()
        self.Help_label_3.raise_()
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(40, 40, 50, 50))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.text_label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Vũ Nguyễn Trung Hiếu: 23122028</p></body></html>"))
        self.text_label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Châu Văn Minh Khoa: 23122035</p></body></html>"))
        self.text_label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Phan Ngọc Quân: 23122046</p></body></html>"))
        self.text_label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Đoàn Quang Thắng: 23122051</p></body></html>"))
        self.text_label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">GVHD: Tung Le - Minh Nguyen</p></body></html>"))
        self.Help_label_3.setText(_translate("MainWindow", " ABOUT"))
        self.back_button.setIcon(QIcon("Do_an/UI/image/back.png"))
        self.back_button.clicked.connect(lambda: self.menu(MainWindow))

        #khởi tạo âm thanh
        self.sound = Sound()
        self.sound.setUp()

    def menu(self, MainWindow):
        from UI.user_interface.menu import MenuWidget
        self.sound.clickSound()
        #self.sound.pause_bgSound()
        self.MenuWindow = QtWidgets.QMainWindow()
        self.Menu = MenuWidget()
        self.Menu.setupUi(self.MenuWindow)
        self.MenuWindow.show()
        MainWindow.close()