from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from UI.user_interface.music import Sound

class HelpWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(36)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Help_label = QtWidgets.QLabel(self.centralwidget)
        self.Help_label.setGeometry(QtCore.QRect(270, 30, 241, 131))
        font = QtGui.QFont()
        font.setFamily("Freestyle Script")
        font.setPointSize(72)
        self.Help_label.setFont(font)
        self.Help_label.setObjectName("Help_label")
        self.Move_label = QtWidgets.QLabel(self.centralwidget)
        self.Move_label.setGeometry(QtCore.QRect(410, 370, 201, 141))
        self.Move_label.setText("")
        self.Move_label.setPixmap(QtGui.QPixmap("../test file/12.png"))
        self.Move_label.setObjectName("Move_label")
        self.text_label = QtWidgets.QLabel(self.centralwidget)
        self.text_label.setGeometry(QtCore.QRect(20, 370, 371, 121))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(18)
        self.text_label.setFont(font)
        self.text_label.setObjectName("text_label")
        self.text_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.text_label_2.setGeometry(QtCore.QRect(20, 200, 611, 61))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(18)
        self.text_label_2.setFont(font)
        self.text_label_2.setObjectName("text_label_2")
        self.text_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.text_label_3.setGeometry(QtCore.QRect(20, 260, 441, 61))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(18)
        self.text_label_3.setFont(font)
        self.text_label_3.setObjectName("text_label_3")
        self.text_label_4 = QtWidgets.QLabel(self.centralwidget)
        self.text_label_4.setGeometry(QtCore.QRect(20, 140, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(18)
        self.text_label_4.setFont(font)
        self.text_label_4.setObjectName("text_label_4")
        self.text_label_5 = QtWidgets.QLabel(self.centralwidget)
        self.text_label_5.setGeometry(QtCore.QRect(20, 360, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(18)
        self.text_label_5.setFont(font)
        self.text_label_5.setText("")
        self.text_label_5.setObjectName("text_label_5")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(40, 40, 50, 50))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Help_label.setText(_translate("MainWindow", " HELP"))
        self.text_label.setText(_translate("MainWindow", "<html><head/><body><p>Sử dụng các phím di chuyển </p><p>để điều khiển nhân vật</p></body></html>"))
        self.text_label_2.setText(_translate("MainWindow", "Chọn chế độ chơi trong New Game rồi ấn Play"))
        self.text_label_3.setText(_translate("MainWindow", "Tải lại trò chơi trong Load Game"))
        self.text_label_4.setText(_translate("MainWindow", "How to Play?"))
        self.back_button.setIcon(QIcon("Do_an/UI/image/back.png"))
        self.back_button.clicked.connect(lambda: self.menu(MainWindow))

        #khởi tạo âm thanh
        self.sound = Sound()
        self.sound.setUp()

    def menu(self, MainWindow):
        from UI.user_interface.menu import MenuWidget
        self.sound.clickSound()
        #self.sound.pause_bgSound()
        self.MenuWindow = QtWidgets.QMainWindow()
        self.Menu = MenuWidget()
        self.Menu.setupUi(self.MenuWindow)
        self.MenuWindow.show()
        MainWindow.close()